name: Run Unit Tests

on:
  push:
    branches:
      - feature/*
    pull_request:
      branches:
        - main

jobs:
  run-unit-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Create Virtual Environment
        run: python -m venv .venv && source .venv/bin/activate

      - name: Install Dependencies
        run: python -m pip install '.[dev]'

      - name: Run Unit Tests
        run: python -m unittest discover -s tests/unit -p 'test_*.py'

      - name: Run Black
        run: python -m black --check . --diff